stages:
  - build
  - deploy

variables:
  GITLAB_TOKEN: "REDACTED_gitlab_pat­_db_ci_deploy"

build_job:
  stage: build
  script:
    - echo "Building..."
deploy_job:
  stage: deploy
  script:
    - echo "Deploying to db-primary"
  only:
    - master
